services:
 
  nginx:
    container_name: nginx-container
    build:
      context: ..
      dockerfile: srcs/requirements/nginx/Dockerfile
    image: nginx
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: ${HOME}/data/wordpress
        target: /var/www/html
    networks:
      - website
    restart: on-failure
 
  wordpress:
    container_name: wordpress-container
    build:
      context: ..
      dockerfile: srcs/requirements/wordpress/Dockerfile
    image: wordpress
    volumes:
      - type: bind
        source: ${HOME}/data/wordpress
        target: /var/www/html
    networks:
      - website
    depends_on:
      - mariadb
    env_file: .env
    restart: on-failure
  
  mariadb:
    container_name: mariadb-container
    build:
      context: ..
      dockerfile: srcs/requirements/mariadb/Dockerfile
    image: mariadb
    env_file: .env
    volumes:
      - type: bind
        source: ${HOME}/data/db
        target: /var/lib/mysql
    networks:
      - website
    restart: on-failure

  redis-cache:
    container_name: redis-cache-container
    build:
      context: ..
      dockerfile: srcs/requirements/redis-cache/Dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    image: redis-cache
    env_file: .env
    networks:
      - website
    restart: on-failure

networks:
  website:
