services:

  nginx:
    container_name: nginx-container
    build:
      context: requirements/nginx
    image: nginx
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - wordpress_vol:/var/www/html
      - adminer_vol:/var/www/adminer
    networks:
      - website
    restart: on-failure
    env_file: .env

  wordpress:
    container_name: wordpress-container
    build:
      context: requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - website
    depends_on:
      - mariadb
    env_file: .env
    restart: on-failure

  mariadb:
    container_name: mariadb-container
    build:
      context: requirements/mariadb
    image: mariadb
    env_file: .env
    volumes:
      - database_vol:/var/lib/mysql
    networks:
      - website
    restart: on-failure

  redis-cache:
    container_name: redis-cache-container
    build:
      context: requirements/redis-cache
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    image: redis-cache
    env_file: .env
    networks:
      - website
    restart: on-failure

  vsftpd:
    container_name: vsftpd-container
    build:
      context: requirements/vsftpd
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
    image: vsftpd
    volumes:
      - wordpress_vol:/home/${FTP_USER}/wordpress
    restart: on-failure
    ports:
      - "21:21"
      - "20:20"
      - "990:990"
      - "5000-5042:5000-5042"

  adminer:
    container_name: adminer-container
    build:
      context: requirements/adminer
    image: adminer
    env_file: .env
    networks:
      - website
    restart: on-failure
    volumes:
      - adminer_vol:/var/www/adminer

  static-site:
    container_name: static-site-container
    build:
      context: ..
      dockerfile: srcs/requirements/static-site/Dockerfile
    image: static-site
    env_file: .env
    restart: on-failure
    ports:
      - "8081:8081"

networks:
  website:

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      device: ${WORDPRESS_VOLUME}
      type: volume
      o: bind
  database_vol:
    driver: local
    driver_opts:
      device: ${DATABASE_VOLUME}
      type: volume
      o: bind
  adminer_vol:
    driver: local
    driver_opts:
      device: ${ADMINER_VOLUME}
      type: volume
      o: bind
