services:
 
  nginx:
    build:
      context: ..
      dockerfile: srcs/requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - website
    restart: always
 
  wordpress:
    build:
      context: ..
      dockerfile: srcs/requirements/wordpress/Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - website
    depends_on:
      - mariadb
    env_file: .env
    restart: always
  
  mariadb:
    build:
      context: ..
      dockerfile: srcs/requirements/mariadb/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - website
    restart: always

volumes:
  wordpress:
  db:

networks:
  website:
