services:
 
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - website
 
  wordpress:
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: patate
      WORDPRESS_DB_PASSWORD: maizena
      WORDPRESS_DB_NAME: patatedb
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://skoulen.42.fr');
        define('WP_SITEURL', 'https://skoulen.42.fr');
    volumes:
      - wordpress:/var/www/html
    networks:
      - website
  
  mariadb:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: patatedb
      MARIADB_USER: patate
      MARIADB_PASSWORD: maizena
    volumes:
      - db:/var/lib/mysql
    networks:
      - website

volumes:
  wordpress:
  db:

networks:
  website:
