services:
 
  nginx:
    container_name: nginx-container
    build:
      context: requirements/nginx
    image: nginx
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - type: bind
        source: ${HOME}/data/wordpress
        target: /var/www/html
      - adminer_vol:/var/www/adminer
    networks:
      - website
    restart: on-failure
 
  wordpress:
    container_name: wordpress-container
    build:
      context: requirements/wordpress
    image: wordpress
    volumes:
      - type: bind
        source: ${HOME}/data/wordpress
        target: /var/www/html
    networks:
      - website
    depends_on:
      - mariadb
    env_file: .env
    restart: on-failure
  
  mariadb:
    container_name: mariadb-container
    build:
      context: requirements/mariadb
    image: mariadb
    env_file: .env
    volumes:
      - type: bind
        source: ${HOME}/data/db
        target: /var/lib/mysql
    networks:
      - website
    restart: on-failure

  redis-cache:
    container_name: redis-cache-container
    build:
      context: srcs/requirements/redis-cache
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    image: redis-cache
    env_file: .env
    networks:
      - website
    restart: on-failure

  vsftpd:
    container_name: vsftpd-container
    build:
      context: srcs/requirements/vsftpd
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
    image: vsftpd
    networks:
      - website
    restart: on-failure
    ports:
      - "21:21"
      - "20:20"
      - "990:990"
      - "5000-5042:5000-5042"

  adminer:
    container_name: adminer-container
    build:
      context: srcs/requirements/adminer
    image: adminer
    env_file: .env
    networks:
      - website
    restart: on-failure
    volumes:
      - adminer_vol:/var/www/adminer

  static-site:
    container_name: static-site-container
    build:
      context: srcs/requirements/static-site
    image: static-site
    env_file: .env
    restart: on-failure
    ports:
      - "8081:8081"

networks:
  website:

volumes:
  adminer_vol:
