services:
 
  nginx:
    build:
      context: ..
      dockerfile: srcs/requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: ${HOME}/data/wordpress
        target: /var/www/html
    networks:
      - website
    restart: on-failure
 
  wordpress:
    build:
      context: ..
      dockerfile: srcs/requirements/wordpress/Dockerfile
    volumes:
      - type: bind
        source: ${HOME}/data/wordpress
        target: /var/www/html
    networks:
      - website
    depends_on:
      - mariadb
    env_file: .env
    restart: on-failure
  
  mariadb:
    build:
      context: ..
      dockerfile: srcs/requirements/mariadb/Dockerfile
    env_file: .env
    volumes:
      - type: bind
        source: ${HOME}/data/db
        target: /var/lib/mysql
    networks:
      - website
    restart: on-failure

networks:
  website:
