services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "8080:80"
  wordpress:
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
  mariadb:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile

