services:
 
  nginx:
    build:
      context: ..
      dockerfile: srcs/requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - website
 
  wordpress:
    build:
      context: ..
      dockerfile: srcs/requirements/wordpress/Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://${DOMAIN}');
        define('WP_SITEURL', 'https://${DOMAIN}');
    volumes:
      - wordpress:/var/www/html
    networks:
      - website
    depends_on:
      - mariadb
  
  mariadb:
    build:
      context: ..
      dockerfile: srcs/requirements/mariadb/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - website

volumes:
  wordpress:
  db:

networks:
  website:
