base_url = "http://localhost:8081"
title = "Inception"

theme = "apollo"

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true

[extra]

toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/not_matthias", icon = "twitter" },
    { name = "github", url = "https://github.com/not-matthias/", icon = "github" },
]
