base_url = "http://localhost:8081"
title = "Inception"

theme = "apollo"

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true

[extra]

toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"

menu = [
    { name = "/home", url = "/", weight = 3 },
    { name = "/containers", url = "/containers", weight = 1 },
]

socials = [
    { name = "github", url = "https://github.com/sophiakoulen/Inception", icon = "github" },
]
